apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: namespace2  # This ensures the service is in the second namespace
spec:
  selector:
    app: my-app  # This must match the label from the deployment
  ports:
    - protocol: TCP
      port: 80  # Port the service will expose
      targetPort: 80  # Port the container listens on
  type: ClusterIP  # Default type; you can use NodePort to expose it outside the cluster
